DESIGN_CONFIG_PATH ?= .
RTL_SV_SRC ?=
RTL_SV_INCDIRS ?=

RTL_ROOT := $(PULP_COMMON_PATH)/src

RTL_SV_SRC += $(RTL_ROOT)/fifo_v3.sv
RTL_SV_SRC := $(RTL_SV_SRC)

RTL_ROOT := $(DESIGN_CONFIG_PATH)/../src

RTL_SV_SRC += $(RTL_ROOT)/axi_id_prepend.sv
RTL_SV_SRC += $(RTL_ROOT)/axi_mux.sv

RTL_SV_DEFINES +=

RTL_SV_INCDIRS += $(DESIGN_CONFIG_PATH)/../include
RTL_SV_INCDIRS += $(PULP_COMMON_PATH)/include
RTL_SV_INCDIRS := $(RTL_SV_INCDIRS)

RTL_TOP := axi_mux

